#@TYPE: Machine
#@NAME: milkv-duo
#@SOC: CVITEK CV1800B
#@DESCRIPTION: Machine configuration for Milk-V Duo

require conf/machine/include/milkv-cv180x.inc

MACHINE_NAME = "milkv-duo"

UBOOT_MACHINE ?= "milkv-duo_defconfig"
KERNEL_DEVICETREE ?= "sophgo/cv1800b-milkv-duo.dtb"

WKS_FILE ?= "milkv-duo.wks"
