/* SPDX-License-Identifier: MIT WITH Linux-syscall-note */
/*
 * Sophgo SG2000 TPU Accelerator - Userspace API
 *
 * Copyright (C) 2026 meta-riscv contributors
 *
 * Based on Sophgo vendor driver (GPL-2.0) from sophgo/osdrv
 * Reimplemented as Linux DRM/accel subsystem driver
 */

#ifndef __UAPI_SOPHGO_TPU_H__
#define __UAPI_SOPHGO_TPU_H__

#include <drm/drm.h>

#if defined(__cplusplus)
extern "C" {
#endif

/*
 * IOCTL definitions for the Sophgo TPU accel driver.
 *
 * The driver exposes /dev/accel/accelN and uses GEM for buffer management.
 * Workflow:
 *   1. CREATE_BO  - allocate a GEM buffer (for weights, activations, cmdbuf)
 *   2. MMAP_BO    - get mmap offset for the buffer
 *   3. SUBMIT     - submit a command buffer (dmabuf) to the TPU
 *   4. WAIT       - wait for TPU execution to complete
 *   5. GEM_CLOSE  - free the buffer (standard DRM_IOCTL_GEM_CLOSE)
 */

/* Buffer creation flags */
#define SOPHGO_TPU_BO_CACHED		(1 << 0)

/* Sync direction flags */
#define SOPHGO_TPU_SYNC_FLUSH		(1 << 0)  /* CPU -> Device */
#define SOPHGO_TPU_SYNC_INVALIDATE	(1 << 1)  /* Device -> CPU */

/**
 * struct drm_sophgo_tpu_create_bo - Create a GEM buffer object
 * @size:    [in]  Requested buffer size in bytes (page-aligned by driver)
 * @flags:   [in]  SOPHGO_TPU_BO_CACHED or 0
 * @handle:  [out] GEM handle for the buffer
 * @offset:  [out] Fake mmap offset for use with mmap(2) on the drm fd
 * @paddr:   [out] Physical/DMA address (needed by TPU command buffers)
 */
struct drm_sophgo_tpu_create_bo {
	__u64 size;
	__u32 flags;
	__u32 handle;
	__u64 offset;
	__u64 paddr;
};

/**
 * struct drm_sophgo_tpu_mmap_bo - Get mmap offset for existing BO
 * @handle:  [in]  GEM handle
 * @offset:  [out] Fake mmap offset
 */
struct drm_sophgo_tpu_mmap_bo {
	__u32 handle;
	__u32 pad;
	__u64 offset;
};

/**
 * struct drm_sophgo_tpu_submit - Submit a command buffer to the TPU
 * @cmdbuf_handle: [in]  GEM handle of the command/DMA buffer
 * @cmdbuf_size:   [in]  Size of valid data in the command buffer
 * @seq_no:        [out] Sequence number for tracking (use with WAIT)
 *
 * The command buffer must contain a properly formatted TPU dmabuf
 * (header + TIU descriptors + TDMA descriptors), as generated by
 * libcvikernel/libcviruntime.
 */
struct drm_sophgo_tpu_submit {
	__u32 cmdbuf_handle;
	__u32 cmdbuf_size;
	__u32 seq_no;
	__u32 pad;
};

/**
 * struct drm_sophgo_tpu_wait - Wait for a submitted job to complete
 * @seq_no:     [in]  Sequence number from SUBMIT
 * @timeout_ms: [in]  Timeout in milliseconds (0 = infinite)
 * @status:     [out] 0 = success, negative = error
 */
struct drm_sophgo_tpu_wait {
	__u32 seq_no;
	__u32 timeout_ms;
	__s32 status;
	__u32 pad;
};

/**
 * struct drm_sophgo_tpu_sync - Cache maintenance for a buffer
 * @handle: [in] GEM handle
 * @flags:  [in] SOPHGO_TPU_SYNC_FLUSH and/or SOPHGO_TPU_SYNC_INVALIDATE
 * @offset: [in] Offset within buffer (0 for entire buffer)
 * @size:   [in] Size to sync (0 for entire buffer)
 */
struct drm_sophgo_tpu_sync {
	__u32 handle;
	__u32 flags;
	__u64 offset;
	__u64 size;
};

/* DRM ioctl numbers — base offset from DRM_COMMAND_BASE */
#define DRM_SOPHGO_TPU_CREATE_BO	0x00
#define DRM_SOPHGO_TPU_MMAP_BO		0x01
#define DRM_SOPHGO_TPU_SUBMIT		0x02
#define DRM_SOPHGO_TPU_WAIT		0x03
#define DRM_SOPHGO_TPU_SYNC		0x04

#define DRM_IOCTL_SOPHGO_TPU_CREATE_BO	DRM_IOWR(DRM_COMMAND_BASE + DRM_SOPHGO_TPU_CREATE_BO, struct drm_sophgo_tpu_create_bo)
#define DRM_IOCTL_SOPHGO_TPU_MMAP_BO	DRM_IOWR(DRM_COMMAND_BASE + DRM_SOPHGO_TPU_MMAP_BO, struct drm_sophgo_tpu_mmap_bo)
#define DRM_IOCTL_SOPHGO_TPU_SUBMIT	DRM_IOWR(DRM_COMMAND_BASE + DRM_SOPHGO_TPU_SUBMIT, struct drm_sophgo_tpu_submit)
#define DRM_IOCTL_SOPHGO_TPU_WAIT	DRM_IOWR(DRM_COMMAND_BASE + DRM_SOPHGO_TPU_WAIT, struct drm_sophgo_tpu_wait)
#define DRM_IOCTL_SOPHGO_TPU_SYNC	DRM_IOW(DRM_COMMAND_BASE + DRM_SOPHGO_TPU_SYNC, struct drm_sophgo_tpu_sync)

#if defined(__cplusplus)
}
#endif

#endif /* __UAPI_SOPHGO_TPU_H__ */
